import sys
sys.path.append('/home/pi/Desktop/Github/Raspberry')
import MessageServer

import pyautogui
import os
from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import(
        QMainWindow
)

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        # self.setupUi()
        self.threadpool = QThreadPool()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MenuBg = QtWidgets.QFrame(self.centralwidget)
        self.MenuBg.setGeometry(QtCore.QRect(-1, -1, 171, 601))
        self.MenuBg.setStyleSheet("background-color: rgb(30, 127, 255);")
        self.MenuBg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MenuBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuBg.setObjectName("MenuBg")
        self.label = QtWidgets.QLabel(self.MenuBg)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 61))
        font = QtGui.QFont()
        font.setFamily("LEMON MILK Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.MenuBg)
        self.label_2.setGeometry(QtCore.QRect(100, 30, 47, 21))
        font = QtGui.QFont()
        font.setFamily("LEMON MILK Bold")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.ButtonLogout = QtWidgets.QPushButton(self.MenuBg)
        self.ButtonLogout.setGeometry(QtCore.QRect(50, 570, 61, 21))
        self.ButtonLogout.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ButtonLogout.setObjectName("ButtonLogout")
        self.MenuButton = QtWidgets.QFrame(self.MenuBg)
        self.MenuButton.setGeometry(QtCore.QRect(10, 110, 151, 241))
        self.MenuButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"LEMON MILK Bold\";")
        self.MenuButton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MenuButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuButton.setObjectName("MenuButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.MenuButton)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 151, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ButtonAutoStart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonAutoStart.setObjectName("ButtonAutoStart")
        self.verticalLayout.addWidget(self.ButtonAutoStart)
        self.ButtonDashboard = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonDashboard.setObjectName("ButtonDashboard")
        self.verticalLayout.addWidget(self.ButtonDashboard)
        self.ButtonHilfe = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonHilfe.setObjectName("ButtonHilfe")
        self.verticalLayout.addWidget(self.ButtonHilfe)
        self.ButtonTerminal = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonTerminal.setObjectName("ButtonTerminal")
        self.verticalLayout.addWidget(self.ButtonTerminal)
        self.ButtonErrorLog = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonErrorLog.setObjectName("ButtonErrorLog")
        self.verticalLayout.addWidget(self.ButtonErrorLog)
        self.WhiteBG = QtWidgets.QFrame(self.centralwidget)
        self.WhiteBG.setGeometry(QtCore.QRect(170, 0, 861, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhiteBG.sizePolicy().hasHeightForWidth())
        self.WhiteBG.setSizePolicy(sizePolicy)
        self.WhiteBG.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WhiteBG.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WhiteBG.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WhiteBG.setObjectName("WhiteBG")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.WhiteBG)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 831, 151))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Modul = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Modul.setContentsMargins(0, 0, 0, 0)
        self.Modul.setObjectName("Modul")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("LEMON MILK Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.LabelAktivHoehenruder = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelAktivHoehenruder.setFont(font)
        self.LabelAktivHoehenruder.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelAktivHoehenruder.setObjectName("LabelAktivHoehenruder")
        self.verticalLayout_2.addWidget(self.LabelAktivHoehenruder)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.LabelModul1Pakete = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelModul1Pakete.setFont(font)
        self.LabelModul1Pakete.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelModul1Pakete.setObjectName("LabelModul1Pakete")
        self.verticalLayout_2.addWidget(self.LabelModul1Pakete)
        self.Modul.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("LEMON MILK Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.LabelAktivSeitenruder = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelAktivSeitenruder.setFont(font)
        self.LabelAktivSeitenruder.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelAktivSeitenruder.setObjectName("LabelAktivSeitenruder")
        self.verticalLayout_3.addWidget(self.LabelAktivSeitenruder)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.LabelModul2Pakete = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelModul2Pakete.setFont(font)
        self.LabelModul2Pakete.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelModul2Pakete.setObjectName("LabelModul2Pakete")
        self.verticalLayout_3.addWidget(self.LabelModul2Pakete)
        self.Modul.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("LEMON MILK Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.LabelAktivQuerruder = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.LabelAktivQuerruder.setFont(font)
        self.LabelAktivQuerruder.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelAktivQuerruder.setObjectName("LabelAktivQuerruder")
        self.verticalLayout_4.addWidget(self.LabelAktivQuerruder)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.LabelModul3Pakete = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelModul3Pakete.setFont(font)
        self.LabelModul3Pakete.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelModul3Pakete.setObjectName("LabelModul3Pakete")
        self.verticalLayout_4.addWidget(self.LabelModul3Pakete)
        self.Modul.addLayout(self.verticalLayout_4)
        self.Offset = QtWidgets.QFrame(self.WhiteBG)
        self.Offset.setGeometry(QtCore.QRect(10, 250, 831, 61))
        self.Offset.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Offset.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Offset.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Offset.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Offset.setObjectName("Offset")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Offset)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 831, 61))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LabelOffsetHoehenruder = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.LabelOffsetHoehenruder.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelOffsetHoehenruder.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelOffsetHoehenruder.setObjectName("LabelOffsetHoehenruder")
        self.horizontalLayout_4.addWidget(self.LabelOffsetHoehenruder)
        self.LabelOffsetSeitenruder = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.LabelOffsetSeitenruder.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelOffsetSeitenruder.setObjectName("LabelOffsetSeitenruder")
        self.horizontalLayout_4.addWidget(self.LabelOffsetSeitenruder)
        self.LabelOffsetQuerruder = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.LabelOffsetQuerruder.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelOffsetQuerruder.setObjectName("LabelOffsetQuerruder")
        self.horizontalLayout_4.addWidget(self.LabelOffsetQuerruder)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.WhiteBG)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 320, 831, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LabelBatterieHoehenruder = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LabelBatterieHoehenruder.setFont(font)
        self.LabelBatterieHoehenruder.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelBatterieHoehenruder.setObjectName("LabelBatterieHoehenruder")
        self.horizontalLayout.addWidget(self.LabelBatterieHoehenruder)
        self.LabelBatterieSeitenruder = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelBatterieSeitenruder.setFont(font)
        self.LabelBatterieSeitenruder.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelBatterieSeitenruder.setObjectName("LabelBatterieSeitenruder")
        self.horizontalLayout.addWidget(self.LabelBatterieSeitenruder)
        self.LabelBatterieQuerruder = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelBatterieQuerruder.setFont(font)
        self.LabelBatterieQuerruder.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelBatterieQuerruder.setObjectName("LabelBatterieQuerruder")
        self.horizontalLayout.addWidget(self.LabelBatterieQuerruder)
        self.ButtonJoystickHandshake = QtWidgets.QPushButton(self.WhiteBG)
        self.ButtonJoystickHandshake.setGeometry(QtCore.QRect(20, 420, 201, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonJoystickHandshake.sizePolicy().hasHeightForWidth())
        self.ButtonJoystickHandshake.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ButtonJoystickHandshake.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ButtonJoystickHandshake.setFont(font)
        self.ButtonJoystickHandshake.setDefault(True)
        self.ButtonJoystickHandshake.setFlat(True)
        self.ButtonJoystickHandshake.setObjectName("ButtonJoystickHandshake")
        self.line = QtWidgets.QFrame(self.WhiteBG)
        self.line.setGeometry(QtCore.QRect(0, 390, 861, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.LabelHandshakeStatus = QtWidgets.QLabel(self.WhiteBG)
        self.LabelHandshakeStatus.setGeometry(QtCore.QRect(30, 450, 191, 20))
        self.LabelHandshakeStatus.setObjectName("LabelHandshakeStatus")
        self.LabelHandshakeStatus.setFont(font)
        self.ButtonKalibrierung = QtWidgets.QPushButton(self.WhiteBG)
        self.ButtonKalibrierung.setGeometry(QtCore.QRect(10, 190, 829, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonKalibrierung.sizePolicy().hasHeightForWidth())
        self.ButtonKalibrierung.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ButtonKalibrierung.setPalette(palette)
        self.ButtonKalibrierung.setDefault(True)
        self.ButtonKalibrierung.setFlat(True)
        self.ButtonKalibrierung.setObjectName("ButtonKalibrierung")
        self.WhiteBG.raise_()
        self.MenuBg.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.ButtonConf()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FS-Simpro"))
        self.label.setText(_translate("MainWindow", "FS-Sim"))
        self.label_2.setText(_translate("MainWindow", "PRO"))
        self.ButtonLogout.setText(_translate("MainWindow", "Log Out"))
        self.ButtonAutoStart.setText(_translate("MainWindow", "AutoStart"))
        self.ButtonDashboard.setText(_translate("MainWindow", "Dashboard"))
        self.ButtonHilfe.setText(_translate("MainWindow", "Hilfe"))
        self.ButtonTerminal.setText(_translate("MainWindow", "Terminal"))
        self.ButtonErrorLog.setText(_translate("MainWindow", "Error Log"))
        self.label_6.setText(_translate("MainWindow", "Modul 1\n"
" Höhenruder"))
        self.LabelAktivHoehenruder.setText(_translate("MainWindow", "Aktiv: Nein"))
        self.label_8.setText(_translate("MainWindow", "Eingehende Pakete:"))
        self.LabelModul1Pakete.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Modul 2\n"
" Seitenruder"))
        self.LabelAktivSeitenruder.setText(_translate("MainWindow", "Aktiv: Nein"))
        self.label_9.setText(_translate("MainWindow", "Eingehende Pakete:"))
        self.LabelModul2Pakete.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Modul 3\n"
" Querruder"))
        self.LabelAktivQuerruder.setText(_translate("MainWindow", "Aktiv: Nein"))
        self.label_10.setText(_translate("MainWindow", "Eingehende Pakete:"))
        self.LabelModul3Pakete.setText(_translate("MainWindow", "0"))
        self.LabelOffsetHoehenruder.setText(_translate("MainWindow", "Offset: 0°"))
        self.LabelOffsetSeitenruder.setText(_translate("MainWindow", "Offset: 0°"))
        self.LabelOffsetQuerruder.setText(_translate("MainWindow", "Offset: 0°"))
        self.LabelBatterieHoehenruder.setText(_translate("MainWindow", "Batterie:"))
        self.LabelBatterieSeitenruder.setText(_translate("MainWindow", "Batterie:"))
        self.LabelBatterieQuerruder.setText(_translate("MainWindow", "Batterie:"))
        self.ButtonJoystickHandshake.setText(_translate("MainWindow", "Joystick Handshake (manuell)"))
        self.LabelHandshakeStatus.setText(_translate("MainWindow", "Handshake: nicht erfoglreich"))
        self.ButtonKalibrierung.setText(_translate("MainWindow", "Ruder-Kalibrierung (manuell)"))  

    def ButtonConf(self):
        self.server = MessageServer.Server()
        self.ButtonAutoStart.clicked.connect(self.RunTask)
        self.ButtonKalibrierung.clicked.connect(self.server.SensorCalibration)
        # self.ButtonCMD.clicked.connect(self.OpenCMD)
        self.ButtonLogout.clicked.connect(self.LogOut)
        
    def UpdateMessageCount(self):
        self.LabelModul1Pakete.setText(str(self.server.messageCountHoehen/2))
        self.LabelModul2Pakete.setText(str(self.server.messageCountSeiten/2))
        self.LabelModul3Pakete.setText(str(self.server.messageCountQuer/2))
 
    def UpdateOffset(self):
        self.LabelOffsetHoehenruder.setText("Offset: " + str(self.server.offsetHoehen))
        self.LabelOffsetSeitenruder.setText("Offset: " + str(self.server.offsetSeiten))
        self.LabelOffsetQuerruder.setText("Offset: " + str(self.server.offsetQuer))
    
    def UpdateClientStatus(self):
        self.LabelAktivHoehenruder.setText("Status: " + str(self.server.statusHoehen))
        self.LabelAktivQuerruder.setText("Status: " + str(self.server.statusQuer))
        self.LabelAktivSeitenruder.setText("Status: " + str(self.server.statusSeiten))

    def UpdateBatteryStatus(self):
        self.LabelBatterieHoehenruder.setText(str(self.server.BatteryStatusHoehen) + "%")
        self.LabelBatterieSeitenruder.setText(str(self.server.BatteryStatusSeiten) + "%")
        self.LabelBatterieQuerruder.setText(str(self.server.BatteryStatusQuer) + "%")

    def UpdateJoystickStatus(self):
        self.LabelHandshakeStatus.setText("Handshake: " + self.sever.statusJoystick)

    def OpenCMD(self):
        return

    def LogOut(self):
        os.system('sudo shutdown -h 0')
        
    def RunTask(self):
        self.server.signals.finishedMessageCount.connect(self.UpdateMessageCount)
        self.server.signals.finishedOffset.connect(self.UpdateOffset)
        self.server.signals.statusClient.connect(self.UpdateClientStatus)
        self.server.signals.statusBattery.connect(self.UpdateBatteryStatus)
        self.server.signals.statusJoystick.connect(self.UpdateJoystickStatus)
        
        self.threadpool.start(self.server)
        
if __name__ == "__main__":
    # import sys
    app = QtWidgets.QApplication([])
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
